[package]
name = "dope-tls"
version = "0.13.0"
edition = "2024"
rust-version = "1.95"
description = "TCP TLS streams for dope runtime, shin-backed"
license = "MIT"
repository = "https://github.com/dope-rs/tls"
readme = "README.md"

[dependencies]
shin = "0.10"
dope-net = "0.9"
webpki-roots = "1.0"
rustls = { version = "0.23", optional = true }

[features]
rustls = ["dep:rustls"]

[dev-dependencies]
dope = "0.9"
o3 = "0.6"
ring = "0.17"
rcgen = "0.14"
dope-extra = "0.9"
dope-fiber = "0.9"
dope-gen = "0.9"
pin-project = "1"
