[package]
name = "dope-tls"
version = "0.6.0"
edition = "2024"
description = "TCP TLS streams for dope runtime, shin-backed"
license = "MIT"
repository = "https://github.com/dope-rs/tls"
readme = "README.md"

[dependencies]
shin = "0.5"
dope = "0.5"
o3 = "0.2"
libc = "0.2"
webpki-roots = "1.0"
rustls-pki-types = "1"
rustls = { version = "0.23", optional = true }

[features]
rustls = ["dep:rustls"]
mem-stats = ["dope/mem-stats"]

[dev-dependencies]
ring = "0.17"
rcgen = "0.14"
dope-extra = "0.5"
dope-gen = "0.5"
pin-project = "1"

[lints.rust]
rust_2024_compatibility = { level = "warn", priority = -1 }
unsafe_op_in_unsafe_fn = "deny"
unreachable_pub = "deny"
dead_code = "deny"
unused_imports = "deny"

[lints.clippy]
all = { level = "warn", priority = -1 }
missing_safety_doc = "allow"
