[package]
name = "dope-tls"
version = "0.19.0"
edition = "2024"
rust-version = "1.95"
description = "TCP TLS streams for dope runtime, shin-backed"
license = "MIT"
repository = "https://github.com/dope-rs/tls"
readme = "README.md"

[dependencies]
shin = "0.17"
dope = "0.15"
o3 = "=0.16.3"
webpki-roots = "1.0"

[dev-dependencies]
ring = "0.17"
rcgen = "0.14"
dope-fiber = "0.15"
dope-gen = "0.15"
pin-project = "1"
